logging:
  file:
    name: log/app.log
  level:
    com.example.smart_campus_backend.controller: info

spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-461nhenu.sql.tencentcdb.com:25450/SPSMS_Database?serverTimezone=GMT%2B8
    username: root
    password: 5921wjy!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
server:
  port: 8081

user:
  username: wz
  age: 21
  gender: man